CREATE TABLE change_events (
    ingest_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    id               TEXT PRIMARY KEY,
    external_id      TEXT,
    parent_id        TEXT REFERENCES change_events(id),
    user_name        TEXT NOT NULL,
    timestamp        TIMESTAMPTZ NOT NULL,
    event_type       TEXT NOT NULL DEFAULT '',
    description      TEXT NOT NULL DEFAULT '',
    long_description TEXT NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_change_events_timestamp ON change_events (timestamp DESC, id ASC);
CREATE INDEX idx_change_events_event_type ON change_events (event_type);
CREATE INDEX idx_change_events_user_name ON change_events (user_name);
CREATE INDEX idx_change_events_parent_id ON change_events (parent_id);
CREATE INDEX idx_change_events_parent_transition ON change_events (parent_id, event_type, ingest_sequence DESC);
CREATE UNIQUE INDEX idx_change_events_external_id ON change_events (external_id) WHERE external_id IS NOT NULL;

CREATE TABLE change_event_links (
    event_id TEXT    NOT NULL REFERENCES change_events(id) ON DELETE CASCADE,
    position INTEGER NOT NULL CHECK (position >= 0),
    label    TEXT    NOT NULL DEFAULT '',
    url      TEXT    NOT NULL,
    PRIMARY KEY (event_id, position)
);

CREATE TABLE change_event_tags (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL REFERENCES change_events(id) ON DELETE CASCADE,
    key      TEXT NOT NULL,
    value    TEXT NOT NULL DEFAULT ''
);

CREATE INDEX idx_change_event_tags_key_value ON change_event_tags (key, value, event_id);
CREATE UNIQUE INDEX idx_change_event_tags_event_key ON change_event_tags (event_id, key);
